### ISSUE TITLE
Terminates when trying to open man 8 for sudo command

### ISSUE THREAD

**Issue by teod0r** [Adonai/Man-Man#11]
Terminates when trying to open man 8 for sudo command from local storage

**Comment by Adonai** [comment]
Will pick all issues up somewhen at the start of March, now no time, sorry

**Comment by Adonai** [comment]
Ok, sudo uses very old groff syntax, altering the parser atm...

**Comment by Adonai** [comment]
@teod0r , it should work by now.
As it turns out, newer man-pages use groff syntax that is drastically simpler, sudo uses old one.

It works, but don't expect it to work perfectly. You can create another issue for Man2Html parser improvements for old-styled manpages.

**Comment by Adonai** [comment]
Fix version: 1.7.0
