### ISSUE TITLE
Direct link to Local archive

### ISSUE THREAD

**Issue by sgeto** [Adonai/Man-Man#12]
Hey

my internet is pretty slow on my phone and I also think my ISP is blocking connection to the local archive URL (the one that is 35 MB). 
I try many times to download them, but I can get the to download to complete. It very frustrating.
Can you maybe give us the URL to the archive so I can download it with another app or on my laptop and then move it to my phone manually?

Thank you

**Comment by sgeto** [comment]
Haha I cloned the source and grep'ed through it.
I feel really stupid finding out that the archive is hosted here, on the release page.
Would be nice if there was a notice (or link) to them inside the app, though...
Anyways, thank you. For the archive and this great app.

Keep it up!

**Comment by Adonai** [comment]
@sgeto , thanks, I'll alter README.md to mention it :)
