### ISSUE TITLE
Text search

### ISSUE THREAD

**Issue by lightonflux** [Adonai/Man-Man#2]
As search in manpage feature would be nice. Like the web browser feature "search in site".

**Comment by Adonai** [comment]
Got this, will implement in a week or so

**Comment by Adonai** [comment]
Done.

Can you test it so I can check before releasing an update to wild?

**Comment by lightonflux** [comment]
Are the build package to download? I don't have the tools setup to compile it myself.

**Comment by Adonai** [comment]
Here you go,

https://mega.nz/#!gY4XhSrQ!8vaSvSRuNc1pciwyGx9manw9eni-LJCxbhh1D7Kw6gI

**Comment by lightonflux** [comment]
Just tested it and it works great. Although the font is not perfectly aligned. It looks a bit like the font in the input fields is floating a bit above the line below it.

**Comment by Adonai** [comment]
Okay, thanks for testing!

Bad aligning happens in all input fields or in this particular search box? If that's global problem, please create different issue for it with screenshot as I don't experience this bug (maybe different font?).

**Comment by lightonflux** [comment]
The search for man pages is fine it is just the input box in the search panel.

On the device I tested the default font was set. Whatever the ones plus uses.

I might find opportunities to test on other devices. But the feature in itself works flawlessly. A few pixel bug that only appears on some devices shouldn't be release blocking. I find this feature so important that I think it is better to release it to the users than waiting for the graphical problems that isn't to visible and might only effect some configurations/devices.


Am 24. August 2015 18:16:19 MESZ, schrieb "Адонай Элохим" <notifications@github.com>:
>Okay, thanks for testing!
>
>Bad aligning happens in all input fields or in this particular search
>box? If that's global problem, please create different issue for it
>with screenshot as I don't experience this bug (maybe different font?).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Adonai/Man-Man/issues/2#issuecomment-134276718

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by lightonflux** [comment]
On my own device with CM11 it looks fine. Very probably a font or theming issue on the other device.

**Comment by Adonai** [comment]
Ok then! I pushed update to the wild. Wc if you need anything else.
