### ISSUE TITLE
Make Man-Man resizable

### ISSUE THREAD

**Issue by alexanderadam** [Adonai/Man-Man#21]
I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing for Android applications](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

The Samsung documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.

[GitNex added a few more lines to enable resizing support](https://codeberg.org/gitnex/GitNex/pulls/601/files) (and they seem to be necessary):

```diff
Subject: [PATCH] Support Samsung DeX

---
 app/src/main/AndroidManifest.xml | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 8518fe2c..f8c2367c 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -12,6 +12,7 @@
         android:icon="@mipmap/app_logo"
         android:label="@string/app_name"
         android:networkSecurityConfig="@xml/network_security_config"
+        android:resizeableActivity="true"
         android:roundIcon="@mipmap/app_logo_round"
         android:supportsRtl="true"
         tools:targetApi="n">
@@ -60,7 +61,7 @@
             android:name=".activities.RepoDetailActivity"
             android:label="@string/title_activity_repo_detail"
             android:theme="@style/AppTheme.NoActionBar" />
-        <activity android:name=".activities.MainActivity" android:theme="@android:style/Theme.NoTitleBar">
+        <activity android:name=".activities.MainActivity" android:theme="@android:style/Theme.NoTitleBar" android:configChanges="orientation|screenSize|smallestScreenSize|density|screenLayout|uiMode|keyboard|keyboardHidden|navigation">
             <intent-filter>
                 <action android:name="android.intent.action.MAIN" />
 
@@ -84,6 +85,11 @@
         <activity android:name=".activities.AddNewTeamMemberActivity" />
         <activity android:name=".activities.SettingsDraftsActivity" />
 
+        <!-- Version < 3.0. DeX Mode and Screen Mirroring support -->
+        <meta-data android:name="com.samsung.android.keepalive.density" android:value="true"/>
+        <!-- Version >= 3.0. DeX Dual Mode support -->
+        <meta-data android:name="com.samsung.android.multidisplay.keep_process_alive" android:value="true"/>
+
     </application>
 
 </manifest>
```

Samsung also has [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and the client is always nearly squarish:
![Man Man on Samsung Dex / Samsung Galaxy Tab S6](https://user-images.githubusercontent.com/372620/91656411-d19f9500-eab8-11ea-8abd-58e7d6c81f53.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizeable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizeable to create less friction.
**PPS:** [This](https://github.com/TeamNewPipe/NewPipe/pull/3948/files) is how NewPipe fixed it.
**PPPS:** There's also [this blog post](https://blog.iamsuleiman.com/prepare-apps-multi-window-in-android-n/) that looks helpful.
**PPPPS:** Offtopic but somehow related — do you know any possibility to read [dash docs](https://kapeli.com/dash) on Android? There used to be [LovelyDocs](https://blog.kapeli.com/dash-for-ios-android-windows-or-linux) but the app seems to be gone. I [asked the author](https://twitter.com/alexanderadam__/status/1296673695889608705) on Twitter but it seems that I'm not getting a response.

**Comment by Adonai** [comment]
Thanks, I actually paln to rejuvenate Man Man this week

**Comment by Adonai** [comment]
> PPPPS: Offtopic but somehow related — do you know any possibility to read dash docs on Android

Nope, and I also searched for a similar way to read devdocs.io to no avail

**Comment by Adonai** [comment]
There's a lot of stuff to rewrite at Man Man as of now but I think I'll get to this issue this week

**Comment by Adonai** [comment]
Added lines you mentioned to release 2.0.0. Can't test it though as I don't own Samsung phone. Post here after you try it out.

**Comment by alexanderadam** [comment]
Thank you! So therefore it should land [on F-Droid](https://f-droid.org/de/packages/com.adonai.manman/) soonish automatically?

**Comment by Adonai** [comment]
Yes, after F-Droid picks up tag change.

**Comment by Adonai** [comment]
You can also try apk from [releases page](https://github.com/Adonai/Man-Man/releases/tag/2.0.1)

**Comment by Adonai** [comment]
F-Droid just updated the build. Ping here if the bug is still relevant.

**Comment by alexanderadam** [comment]
It's working perfectly! Thank you!
