### ISSUE TITLE
(Feature Request) Support SAF storage - Access 

### ISSUE THREAD

**Issue by 5c0tt-b0t** [Adonai/Man-Man#24]
First let me thank you for this, I first downloaded it in 2017, I liked it & was worried it may never be updated again so I was very glad to see it in Fdroid again after all this time!
**The update is amazing! thank you.**
One feature that caught my eye was "local watched folders"!!!
I use Termux so thought I could use my man page collection, unfortunately thats in `/data/data/`, although Termux (and a lot of other apps) do support SAF to share storage with other apps.
This ability would be a great one, using man pages already on our devices, all offline too.
A limitation of SAF is that it can only share folders in `.../$HOME`  and man pages live in `.../usr/share/man` which would be innaccessible, but a symlink from `.../usr/share/man` to say `.../$HOME/.local/share/man` would fix that:
```bash
ln -s /data/data/com.termux/files/usr/share/man $HOME/.local/share/man
```
Or by appending to the variable `$MANPATH`:
```bash
export MANPATH=${MANPATH}:{$HOME}/.local/share/man
```
So the user has a directory for man pages too, `man` will search standard manpath for matches first, else search the users directory for matches after, as this is in `$HOME` it can be watched legitimately (no symlink at all).
**Thank you!**

**Comment by 5c0tt-b0t** [comment]
> First let me thank you for this, I first downloaded it in 2017, I liked it & was worried it may never be updated again so I was very glad to see it in Fdroid again after all this time!
> **The update is amazing! thank you.**
> One feature that caught my eye was "local watched folders"!!!
> I use Termux so thought I could use my man page collection, unfotunately thats in `/data/data/` but Termux (and a lot of other apps) support SAF to share storage with other apps.
> This ability would be a great one, using man pages already on our devices.
> A limitation of SAF is that it can only share folders in `.../$HOME` and man pages live in `.../usr/share/man` which would be innaccessible, but a symlink from `.../usr/share/man` to say `.../$HOME/.local/share/man` would fix that:
> 
> * `ln -s /data/data/com.termux/files/usr/share/man $HOME/.local/share/man`
> 
> Or by appending to the variable `$MANPATH`:
> 
> * `export MANPATH=${MANPATH}:{$HOME}/.local/share/man`
>   So the user has a directory for man pages too, `man` will search standard manpath for matches first, else search the users directory for matches after, as this is in `$HOME` it can be watched legitimately (no symlink at all).
>   **Thank you!**

**Comment by Adonai** [comment]
Hmm I'll take a look at my spare time but SAF has been a disaster for me so far.

**Comment by 5c0tt-b0t** [comment]
Then allow me to close this, your spare time is better spent on other things (like my other ideas: text-share and offering to open your app instead of man-links), us users can simple `cp -r $MANPATH > /sdcard/man` and there it can be used by man man, phones have increasingly large storage now anyway (mine has 128GB, my friend has double that), it was just an idea, I have heard that SAF is a mess from other devs too.
