### ISSUE TITLE
Crashes when trying to open OpenBSD man package 

### ISSUE THREAD

**Issue by 8191** [Adonai/Man-Man#3]
When trying to open e.g. OpenBSD's [man58.tgz](http://ftp2.eu.openbsd.org/pub/OpenBSD/5.8/amd64/man58.tgz) (after ungzipping) man man crashes.

**Comment by Adonai** [comment]
Wow, first serious bug report!
Thank you sir, I'll take a look at this in early Jan 2016

**Comment by Adonai** [comment]
I've checked the archive file and here are my observations:
The Man Man can explore packages that are gzipped, not tar-gzipped. I'll deal with crash by checking file magic but the whole approach should be different.
Here's what directory structure Man Man understands:
```
/usr/share/man % tree uk
uk
├── man1
│   ├── checkXML5.1.gz
│   ├── kf5-config.1.gz
│   ├── kgendesignerplugin.1.gz
│   ├── kpackagetool5.1.gz
│   └── kvirc.1.gz
├── man7
│   ├── kf5options.7.gz
│   └── qt5options.7.gz
└── man8
    ├── desktoptojson.8.gz
    ├── kbuildsycoca5.8.gz
    ├── kcookiejar5.8.gz
    ├── kded5.8.gz
    ├── kdeinit5.8.gz
    └── meinproc5.8.gz
```

**Comment by Adonai** [comment]
@8191 can you try latest code to test your archive? I mean commit 6a76fe0

**Comment by Adonai** [comment]
Closing due to reimplementation available
